Add now playing panel and some global bindable element
HelloYeew/maisim pull request #163
Opened 2022-09-13 20:34 UTC by HelloYeew

- [ ] Require #150 

This PR is a bit huge since it's introduct a lot of new element that we hard-coded befefore.

# The `NowPlayingPanel`

![image](https://user-images.githubusercontent.com/68165621/190001134-36690d4e-5ba5-4af6-8ec0-99e4ce782459.png)

(See Figma for reference)
I try to design it to make it like some popup on iOS's music app and make it as our style. Now it's usable but I still hard coded the database list since we still now have some 'seed' on the database.

# Introduce `WorkingBeatmap` and `MusicPlayer`

As its name
- `WorkingBeatmap` are handle the two `Bindable` of `BeatmapSet` and `DifficultyLevel`
- `MusicPlayer` are handle the entire track playing system in-game
Since we have these two classes, now all element except the song slider are now use the new bindable instead of the hard-coded one.

# The custom track store is working now

Now we can play the track from the game's folder. I currently set the folder name as `tracks` so if you want to try you can put some track in the `<gamefolder>/tracks` to play with it. We will move to `beatmaps` folder to male it suitable with beatmap folder.

# TODO

- Make auto-next-track
- Fix restart-on-ratio
- Test still fail

2022-09-20 19:37 UTC, HelloYeew commented
Tried to fix it by make the `changeTrack` dispose the old track with if the `workingBeatmap,currentBeatmapSet` has not synced with `MusicPlayer` it will force synced on update.

2022-10-09 21:08 UTC, Game4all requested changes

2022-10-09 21:08 UTC, Game4all commented on maisim/maisim.Game/Graphics/UserInterface/Overlays/WorkingBeatmap.cs
> +    public class WorkingBeatmap : CompositeDrawable
Not a huge fan of the way this currently works. Maybe could be a special bindable subclass instead if it is to be used to manage currently selected beatmap / difficulty game-wide?

2022-10-13 19:23 UTC, HelloYeew commented on maisim/maisim.Game/Graphics/UserInterface/Overlays/NowPlayingOverlay.cs
> +        private void trackChanged(ValueChangedEvent<Track> trackEvent) => changeTrack(workingBeatmap.CurrentBeatmapSet.Value);
I deleted the `trackChanged` since it's working with just use `workingBeatmapChanged` now after refactor to new `CurrentWorkingBeatmap`.

2022-10-29 21:20 UTC, Game4all requested changes

2022-10-29 21:20 UTC, Game4all commented on maisim/maisim.Game/Graphics/UserInterface/Overlays/CurrentWorkingBeatmap.cs
> +    public class CurrentWorkingBeatmap
Would rather have this derive from  `Bindable<Beatmapset>` directly and have any change done to the difficulty level trigger a change of BeatmapSet through `TriggerChanged()`

2022-12-30 14:31 UTC, Game4all approved these changes
let's get this in and move forward

2022-12-30 14:46 UTC, merged